### ISSUE TITLE
could not open port 'COM19'

### ISSUE THREAD

**Issue by Dayusheng** [DFRobot/pinpong-docs#2]
用了闪灯的示例程序、设置了win com口、运行之后出现以下提示、请问一下是什么呢问题？

**Comment by Dayusheng** [comment]
> 用了闪灯的示例程序、设置了win com口、运行之后出现以下提示、请问一下是什么呢问题？
  __________________________________________
 |    ____  _       ____                    |
 |   / __ \(_)___  / __ \____  ____  ____ _ |
 |  / /_/ / / __ \/ /_/ / __ \/ __ \/ __ `/ |
 | / ____/ / / / / ____/ /_/ / / / / /_/ /  |
 |/_/   /_/_/ /_/_/    \____/_/ /_/\__, /   |
 |   v0.3.1  Designed by DFRobot  /____/    |
 |__________________________________________|
 
[01] Python3.6.8 Windows-10-10.0.18362-SP0 Board: UNO
Automatically selected ->  COM19
[10] Opening COM19
[15] Close COM19
[32] Firmata ID: 2.6
[10] Opening COM19...
[20] Waiting 4 seconds(arduino_wait) for Arduino devices to reset...
[22] Arduino compatible device found and connected to COM19
[30] Retrieving Arduino Firmware ID...
[32] Arduino Firmware ID: 2.6 FirmataExpress.ino
[40] Retrieving analog map...
[42] Auto-discovery complete. Found 20 Digital Pins and 6 Analog Pins
------------------------------
All right. PinPong go...
------------------------------


  __________________________________________
 |    ____  _       ____                    |
 |   / __ \(_)___  / __ \____  ____  ____ _ |
 |  / /_/ / / __ \/ /_/ / __ \/ __ \/ __ `/ |
 | / ____/ / / / / ____/ /_/ / / / / /_/ /  |
 |/_/   /_/_/ /_/_/    \____/_/ /_/\__, /   |
 |   v0.3.1  Designed by DFRobot  /____/    |
 |__________________________________________|
 
[01] Python3.6.8 Windows-10-10.0.18362-SP0 Board: UNO
[10] Opening COM19
Traceback (most recent call last):
  File "C:/Users/Sun/Desktop/testpinpong.py", line 8, in <module>
    Board("uno","COM19").begin()      #windows下指定端口初始化
  File "E:\python3.6.8\lib\site-packages\pinpong\board.py", line 861, in begin
    major,minor = self.detect_firmata()
  File "E:\python3.6.8\lib\site-packages\pinpong\board.py", line 952, in detect_firmata
    ser=serial.Serial(self.port, 115200, timeout=3)
  File "E:\python3.6.8\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "E:\python3.6.8\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "E:\python3.6.8\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM19': PermissionError(13, '拒绝访问。', None, 5)

**Comment by Dayusheng** [comment]
> 用了闪灯的示例程序、设置了win com口、运行之后出现以下提示、请问一下是什么呢问题？

解决了
